name:       Wil Cooley's Little Piece of Heaven
description: Blog & notes
url:        https://wcooley.github.io
safe:       true
lsi:        false
pygments:   true
permalink:  none
markdown:   kramdown
